package Paneles;

import Formularios.FormAgregarCliente;
import Formularios.FormAgregarEmpleado;
import Formularios.FormAgregarItem;
import Formularios.FormAgregarPresupuesto;
import Formularios.FormAgregarProveedor;
import Frames.MainFrame;
import Modelos.Presupuestos;
import Modelos.Usuarios;
import dao.ClientesDAO;
import dao.ItemsDAO;
import dao.PresupuestosDAO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.manejadorDePermisos;

public class MainPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    
    public MainPanel(Usuarios usuario, MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        
        manejadorDePermisos permisos = new manejadorDePermisos(usuario);
        
        initComponents();
        
        // comprobar permisos botones
        btnInsertarClientes.setEnabled(permisos.puedeInsertarClientes());
        btnInsertarEmpleados.setEnabled(permisos.puedeInsertarEmpleados());
        btnInsertarItems.setEnabled(permisos.puedeInsertarItems());
        btnInsertarPresupuesto.setEnabled(permisos.puedeInsertarPresupuestos());
        btnInsertarProveedores.setEnabled(permisos.puedeInsertarProveedores());
        
        // comprobar permisos paneles
        panelEstadisticasClientes.setVisible(permisos.puedeConsultarClientes());
        panelEstadisticasItems.setVisible(permisos.puedeConsultarItems());
        panelEstadisticasPresupuestos.setVisible(permisos.puedeConsultarPresupuestos());
        panelTablaItems.setVisible(permisos.puedeConsultarItems());
        panelTablaPresupuestos.setVisible(permisos.puedeConsultarPresupuestos());
                

        // Llenar con valores los combo boxes de mes y anio
        for (int m = 1; m <= 12; m++) cbMonth.addItem(m);
        int anioActual = LocalDate.now().getYear();
        for (int a = anioActual; a >= anioActual - 5; a--) cbYear.addItem(a);

        cargarDatos();
    }
    
    public void cargarDatos() {
        PresupuestosDAO presupuestosDAO = new PresupuestosDAO();
        List<Presupuestos> ultimos = presupuestosDAO.obtenerUltimosPresupuestos();

        DefaultTableModel modeloPresupuestos = new DefaultTableModel(new String[]{"ID", "Nombre", "Estatus", "Fecha"}, 0);
        for (Presupuestos p : ultimos) {
            modeloPresupuestos.addRow(new Object[]{
                p.getIdPresupuesto(),
                p.getNombrePres(),
                p.getEstatus(),
                p.getFechaMovimiento()
            });
        }
        tablaUltimosPresupuestos.setModel(modeloPresupuestos);
        
        // llenar el contenido de los labels de estadisticas
        lbTotalPresupuestos.setText("Total: " + presupuestosDAO.obtenerTotalPresupuestos());
        lbPresupuestosPendientes.setText("Pendientes: " + presupuestosDAO.obtenerPresupuestosPendientes());
        lbPresupuestosMes.setText("Aprobados este mes: " + presupuestosDAO.obtenerPresupuestosAprobadosMes());
        
        ClientesDAO clientesDAO = new ClientesDAO();
        lbClientesTotales.setText("Total: " + clientesDAO.obtenerTotalClientes());
        lbClientesActivosMes.setText(("Activos este mes: " + clientesDAO.obtenerClientesActivosEsteMes()));
        
        ItemsDAO itemsDAO = new ItemsDAO();
        lbItemsTotales.setText("Total: " + itemsDAO.obtenerTotalItems());
        lbItemsStockBajo.setText("Con stock bajo: " + itemsDAO.obtenerItemsConStockBajo());
        
        cbMonth.setSelectedItem(LocalDate.now().getMonthValue());
        cbYear.setSelectedItem(LocalDate.now().getYear());        
        int mes = (Integer) cbMonth.getSelectedItem();
        int anio = (Integer) cbYear.getSelectedItem();
        cargarItemsMasVendidos(mes, anio);
    }
    
    public void cargarItemsMasVendidos(int mesSeleccionado, int anioSeleccionado) {
        DefaultTableModel modeloItems = new DefaultTableModel(new String[]{ "Nombre del Item", "Cantidad Vendida", "Existencia", "Precio"}, 0);

        ItemsDAO itemsDAO = new ItemsDAO();
        List<Object[]> items = itemsDAO.obtenerItemsMasVendidosPorMes(mesSeleccionado, anioSeleccionado);

        for (Object[] fila : items) {
            modeloItems.addRow(fila);
        }

        tablaItemsMasVendidos.setModel(modeloItems);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstadisticas = new javax.swing.JPanel();
        panelEstadisticasPresupuestos = new javax.swing.JPanel();
        lbTotalPresupuestos = new javax.swing.JLabel();
        lbPresupuestosPendientes = new javax.swing.JLabel();
        lbPresupuestosMes = new javax.swing.JLabel();
        lblTablaClientes4 = new javax.swing.JLabel();
        panelEstadisticasClientes = new javax.swing.JPanel();
        lbClientesTotales = new javax.swing.JLabel();
        lbClientesActivosMes = new javax.swing.JLabel();
        lblTablaClientes5 = new javax.swing.JLabel();
        panelEstadisticasItems = new javax.swing.JPanel();
        lbItemsStockBajo = new javax.swing.JLabel();
        lbItemsTotales = new javax.swing.JLabel();
        lblTablaClientes6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInsertarPresupuesto = new javax.swing.JButton();
        btnInsertarProveedores = new javax.swing.JButton();
        btnInsertarEmpleados = new javax.swing.JButton();
        btnInsertarClientes = new javax.swing.JButton();
        btnInsertarItems = new javax.swing.JButton();
        lblAtajos = new javax.swing.JLabel();
        lblEstadisticas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelTablaItems = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaItemsMasVendidos = new javax.swing.JTable();
        cbMonth = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        lblTablaClientes1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        panelTablaPresupuestos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUltimosPresupuestos = new javax.swing.JTable();
        lblTablaClientes2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 740));

        panelEstadisticas.setBackground(new java.awt.Color(255, 255, 255));

        panelEstadisticasPresupuestos.setBackground(new java.awt.Color(255, 255, 255));

        lbTotalPresupuestos.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbTotalPresupuestos.setText("Total presupuestos");

        lbPresupuestosPendientes.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbPresupuestosPendientes.setText("Presupuestos pendientes");

        lbPresupuestosMes.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbPresupuestosMes.setText("Presupuestos aprobados este mes");

        lblTablaClientes4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTablaClientes4.setText("Presupuestos");

        javax.swing.GroupLayout panelEstadisticasPresupuestosLayout = new javax.swing.GroupLayout(panelEstadisticasPresupuestos);
        panelEstadisticasPresupuestos.setLayout(panelEstadisticasPresupuestosLayout);
        panelEstadisticasPresupuestosLayout.setHorizontalGroup(
            panelEstadisticasPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasPresupuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotalPresupuestos)
                    .addComponent(lbPresupuestosMes)
                    .addComponent(lbPresupuestosPendientes)
                    .addComponent(lblTablaClientes4))
                .addContainerGap())
        );
        panelEstadisticasPresupuestosLayout.setVerticalGroup(
            panelEstadisticasPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasPresupuestosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTablaClientes4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalPresupuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPresupuestosMes)
                .addGap(18, 18, 18)
                .addComponent(lbPresupuestosPendientes)
                .addContainerGap())
        );

        panelEstadisticasClientes.setBackground(new java.awt.Color(255, 255, 255));

        lbClientesTotales.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbClientesTotales.setText("Clientes totales");

        lbClientesActivosMes.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbClientesActivosMes.setText("Activos este mes:");

        lblTablaClientes5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTablaClientes5.setText("Clientes");

        javax.swing.GroupLayout panelEstadisticasClientesLayout = new javax.swing.GroupLayout(panelEstadisticasClientes);
        panelEstadisticasClientes.setLayout(panelEstadisticasClientesLayout);
        panelEstadisticasClientesLayout.setHorizontalGroup(
            panelEstadisticasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClientesActivosMes)
                    .addComponent(lbClientesTotales)
                    .addComponent(lblTablaClientes5))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelEstadisticasClientesLayout.setVerticalGroup(
            panelEstadisticasClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTablaClientes5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbClientesTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbClientesActivosMes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEstadisticasItems.setBackground(new java.awt.Color(255, 255, 255));

        lbItemsStockBajo.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbItemsStockBajo.setText("Items con stock bajo");

        lbItemsTotales.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N
        lbItemsTotales.setText("Items totales");

        lblTablaClientes6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTablaClientes6.setText("Items");

        javax.swing.GroupLayout panelEstadisticasItemsLayout = new javax.swing.GroupLayout(panelEstadisticasItems);
        panelEstadisticasItems.setLayout(panelEstadisticasItemsLayout);
        panelEstadisticasItemsLayout.setHorizontalGroup(
            panelEstadisticasItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbItemsTotales)
                    .addComponent(lbItemsStockBajo)
                    .addComponent(lblTablaClientes6))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panelEstadisticasItemsLayout.setVerticalGroup(
            panelEstadisticasItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTablaClientes6)
                .addGap(12, 12, 12)
                .addComponent(lbItemsTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbItemsStockBajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEstadisticasLayout = new javax.swing.GroupLayout(panelEstadisticas);
        panelEstadisticas.setLayout(panelEstadisticasLayout);
        panelEstadisticasLayout.setHorizontalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstadisticasPresupuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelEstadisticasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelEstadisticasItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelEstadisticasLayout.setVerticalGroup(
            panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEstadisticasItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelEstadisticasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEstadisticasPresupuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnInsertarPresupuesto.setBackground(new java.awt.Color(248, 250, 252));
        btnInsertarPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarPresupuesto.setForeground(new java.awt.Color(102, 112, 133));
        btnInsertarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-presupuesto-20 (1).png"))); // NOI18N
        btnInsertarPresupuesto.setText("Presupuestos");
        btnInsertarPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarPresupuestoMouseClicked(evt);
            }
        });
        btnInsertarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPresupuestoActionPerformed(evt);
            }
        });

        btnInsertarProveedores.setBackground(new java.awt.Color(248, 250, 252));
        btnInsertarProveedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarProveedores.setForeground(new java.awt.Color(102, 112, 133));
        btnInsertarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-proveedor-20 (1).png"))); // NOI18N
        btnInsertarProveedores.setText("Proveedores");
        btnInsertarProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarProveedoresMouseClicked(evt);
            }
        });
        btnInsertarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarProveedoresActionPerformed(evt);
            }
        });

        btnInsertarEmpleados.setBackground(new java.awt.Color(248, 250, 252));
        btnInsertarEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarEmpleados.setForeground(new java.awt.Color(102, 112, 133));
        btnInsertarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-farmer-20.png"))); // NOI18N
        btnInsertarEmpleados.setText("Empleados");
        btnInsertarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarEmpleadosMouseClicked(evt);
            }
        });
        btnInsertarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmpleadosActionPerformed(evt);
            }
        });

        btnInsertarClientes.setBackground(new java.awt.Color(248, 250, 252));
        btnInsertarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarClientes.setForeground(new java.awt.Color(102, 112, 133));
        btnInsertarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-clientes-20 (1).png"))); // NOI18N
        btnInsertarClientes.setText("Clientes");
        btnInsertarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarClientesMouseClicked(evt);
            }
        });
        btnInsertarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarClientesActionPerformed(evt);
            }
        });

        btnInsertarItems.setBackground(new java.awt.Color(248, 250, 252));
        btnInsertarItems.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarItems.setForeground(new java.awt.Color(102, 112, 133));
        btnInsertarItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-planta-en-maceta-20 (1).png"))); // NOI18N
        btnInsertarItems.setText("Items");
        btnInsertarItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarItemsMouseClicked(evt);
            }
        });
        btnInsertarItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertarPresupuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertarItems)
                .addGap(18, 18, 18)
                .addComponent(btnInsertarProveedores)
                .addGap(18, 18, 18)
                .addComponent(btnInsertarEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnInsertarClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarItems, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblAtajos.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAtajos.setText("Atajos de creacion");

        lblEstadisticas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEstadisticas.setText("Estadisticas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelTablaItems.setBackground(new java.awt.Color(255, 255, 255));

        tablaItemsMasVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaItemsMasVendidos);

        lblTablaClientes1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTablaClientes1.setText("Items mas vendidos");

        btnActualizar.setBackground(new java.awt.Color(248, 250, 252));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(102, 112, 133));
        btnActualizar.setText("Actualizar");
        btnActualizar.setPreferredSize(new java.awt.Dimension(88, 24));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablaItemsLayout = new javax.swing.GroupLayout(panelTablaItems);
        panelTablaItems.setLayout(panelTablaItemsLayout);
        panelTablaItemsLayout.setHorizontalGroup(
            panelTablaItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTablaItemsLayout.createSequentialGroup()
                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTablaClientes1))
                .addGap(6, 6, 6))
        );
        panelTablaItemsLayout.setVerticalGroup(
            panelTablaItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaItemsLayout.createSequentialGroup()
                .addComponent(lblTablaClientes1)
                .addGap(2, 2, 2)
                .addGroup(panelTablaItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTablaPresupuestos.setBackground(new java.awt.Color(255, 255, 255));

        tablaUltimosPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUltimosPresupuestos);

        lblTablaClientes2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTablaClientes2.setText("Ultimos presupuestos");

        javax.swing.GroupLayout panelTablaPresupuestosLayout = new javax.swing.GroupLayout(panelTablaPresupuestos);
        panelTablaPresupuestos.setLayout(panelTablaPresupuestosLayout);
        panelTablaPresupuestosLayout.setHorizontalGroup(
            panelTablaPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaPresupuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTablaClientes2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelTablaPresupuestosLayout.setVerticalGroup(
            panelTablaPresupuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaPresupuestosLayout.createSequentialGroup()
                .addComponent(lblTablaClientes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTablaPresupuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(panelTablaItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTablaItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTablaPresupuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadisticas)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtajos))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAtajos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblEstadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPresupuestoMouseClicked
    }//GEN-LAST:event_btnInsertarPresupuestoMouseClicked

    private void btnInsertarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPresupuestoActionPerformed
        FormAgregarPresupuesto formPresupuesto = new FormAgregarPresupuesto(mainFrame.presupuestosPanel);
        formPresupuesto.setVisible(true);
    }//GEN-LAST:event_btnInsertarPresupuestoActionPerformed

    private void btnInsertarItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarItemsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarItemsMouseClicked

    private void btnInsertarItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarItemsActionPerformed
        FormAgregarItem formItem = new FormAgregarItem(mainFrame.catalogoPanel);
        formItem.setVisible(true);
        
    }//GEN-LAST:event_btnInsertarItemsActionPerformed

    private void btnInsertarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadosMouseClicked
    }//GEN-LAST:event_btnInsertarEmpleadosMouseClicked

    private void btnInsertarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadosActionPerformed
        FormAgregarEmpleado formEmpleado = new FormAgregarEmpleado(mainFrame.empleadosPanel);
        formEmpleado.setVisible(true);
    }//GEN-LAST:event_btnInsertarEmpleadosActionPerformed

    private void btnInsertarProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarProveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarProveedoresMouseClicked

    private void btnInsertarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarProveedoresActionPerformed
        FormAgregarProveedor formProveedor = new FormAgregarProveedor(mainFrame.proveedoresPanel);
        formProveedor.setVisible(true);
    }//GEN-LAST:event_btnInsertarProveedoresActionPerformed

    private void btnInsertarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarClientesMouseClicked

    private void btnInsertarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarClientesActionPerformed
        FormAgregarCliente formCliente = new FormAgregarCliente(mainFrame.clientesPanel);
        formCliente.setVisible(true);
    }//GEN-LAST:event_btnInsertarClientesActionPerformed

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // Al seleccionar nuevo mes/año:
        int mes = (Integer) cbMonth.getSelectedItem();
        int anio = (Integer) cbYear.getSelectedItem();
        cargarItemsMasVendidos(mes, anio);
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInsertarClientes;
    private javax.swing.JButton btnInsertarEmpleados;
    private javax.swing.JButton btnInsertarItems;
    private javax.swing.JButton btnInsertarPresupuesto;
    private javax.swing.JButton btnInsertarProveedores;
    private javax.swing.JComboBox<Integer> cbMonth;
    private javax.swing.JComboBox<Integer> cbYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbClientesActivosMes;
    private javax.swing.JLabel lbClientesTotales;
    private javax.swing.JLabel lbItemsStockBajo;
    private javax.swing.JLabel lbItemsTotales;
    private javax.swing.JLabel lbPresupuestosMes;
    private javax.swing.JLabel lbPresupuestosPendientes;
    private javax.swing.JLabel lbTotalPresupuestos;
    private javax.swing.JLabel lblAtajos;
    private javax.swing.JLabel lblEstadisticas;
    private javax.swing.JLabel lblTablaClientes1;
    private javax.swing.JLabel lblTablaClientes2;
    private javax.swing.JLabel lblTablaClientes4;
    private javax.swing.JLabel lblTablaClientes5;
    private javax.swing.JLabel lblTablaClientes6;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelEstadisticasClientes;
    private javax.swing.JPanel panelEstadisticasItems;
    private javax.swing.JPanel panelEstadisticasPresupuestos;
    private javax.swing.JPanel panelTablaItems;
    private javax.swing.JPanel panelTablaPresupuestos;
    private javax.swing.JTable tablaItemsMasVendidos;
    private javax.swing.JTable tablaUltimosPresupuestos;
    // End of variables declaration//GEN-END:variables
}
