package Paneles;

import Formularios.FormAgregarPresupuesto;
import Modelos.Clientes;
import Modelos.Empleados;
import Modelos.Presupuestos;
import Modelos.Usuarios;
import dao.ClientesDAO;
import dao.EmpleadosDAO;
import dao.PresupuestosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import utils.manejadorDePermisos;



public class PresupuestosPanel extends javax.swing.JPanel {

    private boolean mostrarObjetosEliminados = false;
    private Usuarios usuario;

    
    public PresupuestosPanel(Usuarios usuario) {
        this.usuario = usuario;
        manejadorDePermisos permisos = new manejadorDePermisos(usuario);
        
        initComponents();
        
        btnCrearPresupuesto.setEnabled(permisos.puedeInsertarPresupuestos());
        btnEliminarPresupuesto.setEnabled(permisos.puedeEliminarPresupuestos());
        btnReactivarPresupuesto.setEnabled(permisos.puedeEliminarPresupuestos());
        btnVerDetallesPresupuesto.setEnabled(permisos.puedeConsultarPresupuestos());
        ckbMostrarEliminados.setEnabled(permisos.puedeEliminarPresupuestos());
        tablaPresupuestos.setVisible(permisos.puedeConsultarPresupuestos());
        
        cargarDatos();
    }

    public void cargarDatos() {
        PresupuestosDAO presupuestosDAO = new PresupuestosDAO();
        List<Presupuestos> listaPresupuestos = presupuestosDAO.obtenerPresupuestos();
        EmpleadosDAO empleadosDAO = new EmpleadosDAO();
        ClientesDAO clientesDAO = new ClientesDAO();
        
        
        DefaultTableModel model = new DefaultTableModel(new String[]{
            "Id", "Nombre", "Estado", "Cliente", "Empleado", "Fecha"
        }, 0);
        
        for (Presupuestos p : listaPresupuestos) {
           Empleados empleado = empleadosDAO.obtenerEmpleadoPorId(p.getEmpleados_idEmpleados());
           Clientes cliente = clientesDAO.obtenerClientePorId(p.getClientes_idClientes());
           
           if (!mostrarObjetosEliminados) {
               if (p.getEstatusPresupuestos() == 1) {
                    model.addRow(new Object[]{
                        p.getIdPresupuesto(), p.getNombrePres(), p.getEstatus(),
                        cliente.getNombreClie() + " " + cliente.getApellidosClie(), 
                        empleado.getNombreEmp() + " " + empleado.getApellidoEmp(), 
                        p.getFechaMovimiento()
                    });
               }
           } else {
               if (p.getEstatusPresupuestos() == 0) {
                    model.addRow(new Object[]{
                        p.getIdPresupuesto(), p.getNombrePres(), p.getEstatus(),
                        cliente.getNombreClie() + " " + cliente.getApellidosClie(), 
                        empleado.getNombreEmp() + " " + empleado.getApellidoEmp(), 
                        p.getFechaMovimiento()
                    });
               }
           }
        }
        
        tablaPresupuestos.setModel(model);
        
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablaPresupuestos.setRowSorter(sorter);
        
        txtfBuscarPresupuesto.getDocument().addDocumentListener(new DocumentListener() {
            
        public void insertUpdate(DocumentEvent e) {
            filter();
        }

        public void removeUpdate(DocumentEvent e) {
            filter();
        }

        public void changedUpdate(DocumentEvent e) {
            filter();
        }

        private void filter() {
            String text = txtfBuscarPresupuesto.getText();
            if (text.trim().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTablaPresupuestos = new javax.swing.JLabel();
        buscarPresupuestoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuestos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCrearPresupuesto = new javax.swing.JButton();
        btnVerDetallesPresupuesto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBuscarPresupuesto = new javax.swing.JLabel();
        txtfBuscarPresupuesto = new javax.swing.JTextField();
        btnEliminarPresupuesto = new javax.swing.JButton();
        btnReactivarPresupuesto = new javax.swing.JButton();
        ckbMostrarEliminados = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 740));

        lblTablaPresupuestos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTablaPresupuestos.setText("Tabla: Presupuestos");

        buscarPresupuestoPanel.setBackground(new java.awt.Color(255, 255, 255));
        buscarPresupuestoPanel.setForeground(new java.awt.Color(102, 112, 133));

        javax.swing.GroupLayout buscarPresupuestoPanelLayout = new javax.swing.GroupLayout(buscarPresupuestoPanel);
        buscarPresupuestoPanel.setLayout(buscarPresupuestoPanelLayout);
        buscarPresupuestoPanelLayout.setHorizontalGroup(
            buscarPresupuestoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        buscarPresupuestoPanelLayout.setVerticalGroup(
            buscarPresupuestoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tablaPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPresupuestos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearPresupuesto.setBackground(new java.awt.Color(52, 199, 89));
        btnCrearPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCrearPresupuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-añadir-20.png"))); // NOI18N
        btnCrearPresupuesto.setText("Crear presupuesto");
        btnCrearPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPresupuestoMouseClicked(evt);
            }
        });
        btnCrearPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPresupuestoActionPerformed(evt);
            }
        });

        btnVerDetallesPresupuesto.setBackground(new java.awt.Color(248, 250, 252));
        btnVerDetallesPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVerDetallesPresupuesto.setForeground(new java.awt.Color(102, 112, 133));
        btnVerDetallesPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-editar-20.png"))); // NOI18N
        btnVerDetallesPresupuesto.setText("Ver detalles");
        btnVerDetallesPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerDetallesPresupuestoMouseClicked(evt);
            }
        });
        btnVerDetallesPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesPresupuestoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBuscarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-búsqueda-20.png"))); // NOI18N
        lblBuscarPresupuesto.setText("Buscar:");

        txtfBuscarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfBuscarPresupuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarPresupuesto)
                .addGap(18, 18, 18)
                .addComponent(txtfBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPresupuesto)
                    .addComponent(txtfBuscarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnEliminarPresupuesto.setBackground(new java.awt.Color(255, 85, 85));
        btnEliminarPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnEliminarPresupuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPresupuesto.setText("Eliminar");
        btnEliminarPresupuesto.setPreferredSize(new java.awt.Dimension(142, 37));
        btnEliminarPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPresupuestoMouseClicked(evt);
            }
        });
        btnEliminarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPresupuestoActionPerformed(evt);
            }
        });

        btnReactivarPresupuesto.setBackground(new java.awt.Color(52, 199, 89));
        btnReactivarPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnReactivarPresupuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnReactivarPresupuesto.setText("Reactivar");
        btnReactivarPresupuesto.setPreferredSize(new java.awt.Dimension(93, 37));
        btnReactivarPresupuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReactivarPresupuestoMouseClicked(evt);
            }
        });
        btnReactivarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactivarPresupuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnReactivarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerDetallesPresupuesto)
                .addGap(12, 12, 12)
                .addComponent(btnCrearPresupuesto)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerDetallesPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReactivarPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ckbMostrarEliminados.setText("Mostrar objetos eliminados");
        ckbMostrarEliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMostrarEliminadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTablaPresupuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckbMostrarEliminados)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(buscarPresupuestoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTablaPresupuestos)
                    .addComponent(ckbMostrarEliminados))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarPresupuestoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPresupuestoMouseClicked
    }//GEN-LAST:event_btnCrearPresupuestoMouseClicked

    private void btnCrearPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPresupuestoActionPerformed
       FormAgregarPresupuesto formAgregarPresupuesto = new FormAgregarPresupuesto(this);
       formAgregarPresupuesto.setVisible(true);
    }//GEN-LAST:event_btnCrearPresupuestoActionPerformed

    private void txtfBuscarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfBuscarPresupuestoActionPerformed
    }//GEN-LAST:event_txtfBuscarPresupuestoActionPerformed

    private void btnVerDetallesPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerDetallesPresupuestoMouseClicked

    }//GEN-LAST:event_btnVerDetallesPresupuestoMouseClicked

    private void btnVerDetallesPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesPresupuestoActionPerformed
        int selectedRow = tablaPresupuestos.getSelectedRow();
        if (selectedRow != -1) {
            // Get the ID from the table itself
            int idPresupuesto = (int) tablaPresupuestos.getValueAt(selectedRow, 0); // assuming ID is in column 0

            PresupuestosDAO presupuestosDAO = new PresupuestosDAO();
            List<Presupuestos> listaPresupuestos = presupuestosDAO.obtenerPresupuestos();
            // Find the matching Presupuesto in the list
            Presupuestos selectedPresupuesto = null;
            for (Presupuestos p : listaPresupuestos) {
                if (p.getIdPresupuesto() == idPresupuesto) {
                    selectedPresupuesto = p;
                    break;
                }
            }

            if (selectedPresupuesto != null) {
                DetallesPresupuestoPanel nuevoDetallesPresupuesto = new DetallesPresupuestoPanel(selectedPresupuesto, this, usuario);                
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el presupuesto con ID " + idPresupuesto);
            }

        } else {
                JOptionPane.showMessageDialog(null, "Selecciona un presupuesto primero.");
        }
    }//GEN-LAST:event_btnVerDetallesPresupuestoActionPerformed

    private void btnEliminarPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPresupuestoMouseClicked
    }//GEN-LAST:event_btnEliminarPresupuestoMouseClicked

    private void ckbMostrarEliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMostrarEliminadosActionPerformed
        mostrarObjetosEliminados = ckbMostrarEliminados.isSelected();
        cargarDatos();
    }//GEN-LAST:event_ckbMostrarEliminadosActionPerformed

    private void btnReactivarPresupuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReactivarPresupuestoMouseClicked
    }//GEN-LAST:event_btnReactivarPresupuestoMouseClicked

    private void btnReactivarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivarPresupuestoActionPerformed
        if(!mostrarObjetosEliminados) {
            return;
        }

        int row = tablaPresupuestos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un item a reactivar");
            return;
        }

        int presupuestoId = (int) tablaPresupuestos.getValueAt(row, 0);
        String nombrePresupuesto = (String) tablaPresupuestos.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Estas seguro que quieres reactivar este presupuesto: " + nombrePresupuesto + "?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        PresupuestosDAO presupuestosDAO = new PresupuestosDAO();

        try {
            boolean eliminado;
            eliminado = presupuestosDAO.reactivarPresupuesto(presupuestoId);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Presupuesto reactivado");
                cargarDatos(); // actualiza la tabla
            } else {
                JOptionPane.showMessageDialog(this, "Presupuesto no encontrado");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reactivando presupuesto");
        }
    }//GEN-LAST:event_btnReactivarPresupuestoActionPerformed

    private void btnEliminarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPresupuestoActionPerformed
        int row = tablaPresupuestos.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un item a eliminar");
            return;
        }

        int presupuestoId = (int) tablaPresupuestos.getValueAt(row, 0);
        String nombrePresupuesto = (String) tablaPresupuestos.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Estas seguro que quieres eliminar este presupuesto: " + nombrePresupuesto + "?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        PresupuestosDAO presupuestosDAO = new PresupuestosDAO();

        try {
            boolean eliminado;
            eliminado = presupuestosDAO.eliminarPresupuesto(presupuestoId);

            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Presupuesto eliminado");
                cargarDatos(); // actualiza la tabla
            } else {
                JOptionPane.showMessageDialog(this, "Presupuesto no encontrado");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error eliminando presupuesto");
        }
    }//GEN-LAST:event_btnEliminarPresupuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrearPresupuesto;
    private javax.swing.JButton btnEliminarPresupuesto;
    public javax.swing.JButton btnReactivarPresupuesto;
    public javax.swing.JButton btnVerDetallesPresupuesto;
    private javax.swing.JPanel buscarPresupuestoPanel;
    private javax.swing.JCheckBox ckbMostrarEliminados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarPresupuesto;
    private javax.swing.JLabel lblTablaPresupuestos;
    private javax.swing.JTable tablaPresupuestos;
    private javax.swing.JTextField txtfBuscarPresupuesto;
    // End of variables declaration//GEN-END:variables
}
